### ISSUE TITLE
gcc version problem

### ISSUE THREAD

**Issue by irapkaist** [BassyKuo/PSPNET-cudnn5#5]
My environment is ubuntu16.04, cuda 8.0, cudnn5.

My default gcc and g++ version is 5.

When I run make -j8 in PSPNET-cudnn5, there is no problem.

But when I run make matcaffe, mex doesn't support gcc 5. 

So I found method to hack cuda in (https://gist.github.com/wangruohui/679b05fcd1466bb0937f#fix-hdf5-naming-problem)

But It doesn't work to me. 

Is there solution for me? Thanks.

**Comment by irapkaist** [comment]
http://www.cs.jhu.edu/~cxliu/2016/compiling-matcaffe-on-ubuntu-1604.html

This problem is solved. Please refer this size to solve this problem

**Comment by BassyKuo** [comment]
I add it into README. Thanks 😄
